filter:
    excluded_paths:
        - site-setup/includes/auto-install-plugins.php
        - site-setup/includes/class-tgm-plugin-activation.php

build:
	environment:
        php:
            version: 5.6.10
    dependencies:
        before:
            - composer require --dev 10up/wp_mock:dev-master
